# filepath: /c:/Users/DeeAnn/Desktop/HRMSPROJECT/.pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Use a specific version
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0  # Use a specific version
    hooks:
      - id: isort