# Generated by Django 5.1.3 on 2024-11-09 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Warning',
            new_name='EmployeeWarning',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='kin',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='kin',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.department'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late')], default='P', max_length=1),
        ),
    ]
