# Generated by Django 5.1.3 on 2024-11-14 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscustomization',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hrms.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='hrms_user_set', related_query_name='user', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='hrms_user_permissions_set', related_query_name='user', to='auth.permission'),
        ),
    ]
